# Generated by Django 4.2.9 on 2024-11-30 13:25

from django.db import migrations, models
import django.utils.timezone
import home.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('staff_id', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(choices=[('Staff', 'Staff'), ('Guest', 'Guest'), ('Official', 'Official')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active'), ('Blocked', 'Blocked')], default='Active', max_length=20)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('qr_code_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(max_length=100, verbose_name='UPI ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], default='Active', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Payment Detail',
                'verbose_name_plural': 'Payment Details',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_name', models.CharField(max_length=100, verbose_name='Ticket Name')),
                ('ticket_age', models.CharField(choices=[('Adult', 'Adult'), ('Child', 'Child')], max_length=10, verbose_name='Ticket Age Category')),
                ('nationality', models.CharField(choices=[('Indian', 'Indian'), ('Foreigner', 'Foreigner')], max_length=20, verbose_name='Applicable Nationality')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price for this ticket category', max_digits=10, verbose_name='Ticket Price')),
                ('description', models.TextField(blank=True, help_text='Provide a brief description of the show', verbose_name='Description')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], default='Active', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Show',
                'verbose_name_plural': 'Shows',
                'ordering': ['ticket_name', 'ticket_age', 'nationality'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tag Name')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nationality', models.CharField(choices=[('Indian', 'Indian'), ('Foreigner', 'Foreigner')], max_length=20)),
                ('age_category', models.CharField(choices=[('Adult', 'Adult'), ('Child', 'Child')], max_length=10)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('qr_code_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(default=home.models.generate_unique_id, max_length=100, unique=True)),
                ('transaction_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('entry_in', models.BooleanField(default=False)),
                ('entry_out', models.BooleanField(default=False)),
                ('dinosaur_show_in', models.BooleanField(default=False)),
                ('dinosaur_show_out', models.BooleanField(default=False)),
                ('ancient_statues_in', models.BooleanField(default=False)),
                ('ancient_statues_out', models.BooleanField(default=False)),
                ('ice_age_show_in', models.BooleanField(default=False)),
                ('ice_age_show_out', models.BooleanField(default=False)),
                ('photography', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TicketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_category', models.CharField(choices=[('Booking', 'Booking'), ('Pass', 'Pass')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, verbose_name='Service Name')),
                ('description', models.TextField(help_text='Provide details about the service', verbose_name='Description')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], default='Active', max_length=20, verbose_name='Status')),
                ('service_tags', models.ManyToManyField(blank=True, help_text='Select tags related to this service', to='home.tag', verbose_name='Service Tags')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['service_name', 'status'],
            },
        ),
    ]
