# Generated by Django 4.2.9 on 2024-11-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='transaction_id',
            field=models.CharField(max_length=100),
        ),
    ]
