# Generated by Django 4.2.9 on 2024-11-30 19:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_ticket_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
