# Generated by Django 4.2.9 on 2024-12-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_ticket_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='booking_type',
            field=models.CharField(choices=[('Chatbot', 'Chatbot'), ('Web', 'Web'), ('Counter', 'Counter')], default='Chatbot', max_length=20, verbose_name='Booking Type'),
        ),
        migrations.AddField(
            model_name='income',
            name='session_id',
            field=models.CharField(max_length=100, null=True, verbose_name='Session ID'),
        ),
    ]
