# Generated by Django 4.2.9 on 2024-12-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_income_booking_type_income_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='session_id',
            field=models.CharField(default='default_session', max_length=100, verbose_name='Session ID'),
            preserve_default=False,
        ),
    ]
