# Generated by Django 4.2.9 on 2024-12-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_income_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code_pass/'),
        ),
    ]
