# Generated by Django 4.2.9 on 2024-12-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_pass_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='staff_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
