# Generated by Django 4.2.9 on 2024-12-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_pass_staff_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAndShows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(help_text='Provide details about the service or show', verbose_name='Description')),
                ('type', models.CharField(choices=[('service', 'Service'), ('show', 'Show'), ('other', 'Other')], default='service', max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], default='Active', max_length=20, verbose_name='Status')),
                ('ticket_limit', models.IntegerField(blank=True, help_text='Leave empty for services', null=True, verbose_name='Ticket Limit')),
                ('service_tags', models.ManyToManyField(blank=True, help_text='Select tags related to this service or show', to='home.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Service and Show',
                'verbose_name_plural': 'Services and Shows',
                'ordering': ['name', 'status'],
            },
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
