# Generated by Django 4.2.9 on 2024-12-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_serviceandshows_delete_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceandshows',
            name='other_images',
            field=models.ImageField(blank=True, help_text='Upload any other images related to this service/show', null=True, upload_to='service_and_shows/other_images/', verbose_name='Other Images'),
        ),
        migrations.AddField(
            model_name='serviceandshows',
            name='title_image',
            field=models.ImageField(blank=True, help_text='Upload the main title image for the service/show', null=True, upload_to='service_and_shows/title_images/', verbose_name='Title Image'),
        ),
    ]
