# Generated by Django 4.2.9 on 2024-12-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_serviceandshows_other_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='session_id',
            field=models.UUIDField(editable=False),
        ),
    ]
