# Generated by Django 4.2.9 on 2024-12-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_ticket_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='session_id',
            field=models.CharField(editable=False, max_length=400),
        ),
    ]
