# Generated by Django 5.1.4 on 2024-12-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_feedback_ticket_ticket_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='shows', to='home.tag', verbose_name='Tags'),
        ),
    ]
