# Generated by Django 5.1.4 on 2024-12-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_show_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='tags',
        ),
        migrations.AddField(
            model_name='show',
            name='service_tags',
            field=models.ManyToManyField(blank=True, related_name='shows', to='home.tag'),
        ),
    ]
