# Generated by Django 5.1.4 on 2024-12-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_show_tags_show_service_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ancient_t',
            field=models.IntegerField(default=0, verbose_name='Total Ancient Statues Shows'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='dinosaur_t',
            field=models.IntegerField(default=0, verbose_name='Total Dinosaur Shows'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='entry_t',
            field=models.IntegerField(default=0, verbose_name='Total Entries'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ice_age_t',
            field=models.IntegerField(default=0, verbose_name='Total Ice Age Shows'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='photography_t',
            field=models.IntegerField(default=0, verbose_name='Total Photography'),
        ),
    ]
