# Generated by Django 5.1.4 on 2024-12-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_ticket_ancient_t_ticket_dinosaur_t_ticket_entry_t_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ancient_t',
            field=models.BooleanField(default=False, verbose_name='Ancient Statues Show Activity'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dinosaur_t',
            field=models.BooleanField(default=False, verbose_name='Dinosaur Show Activity'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='entry_t',
            field=models.BooleanField(default=False, verbose_name='Entry Activity'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ice_age_t',
            field=models.BooleanField(default=False, verbose_name='Ice Age Show Activity'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='photography_t',
            field=models.BooleanField(default=False, verbose_name='Photography Activity'),
        ),
    ]
