# Generated by Django 5.1.4 on 2024-12-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_ticket_ancient_t_alter_ticket_dinosaur_t_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='entry_t',
            field=models.BooleanField(default=False),
        ),
    ]
