# Generated by Django 5.1.4 on 2024-12-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_ticket_entry_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ancient_t',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dinosaur_t',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ice_age_t',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='photography_t',
            field=models.BooleanField(default=False),
        ),
    ]
