# Generated by Django 5.1.4 on 2024-12-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_ticket_ancient_t_alter_ticket_dinosaur_t_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Enter the discount percentage (e.g., 10.00 for 10%)', max_digits=5, verbose_name='Discount Percentage'),
        ),
        migrations.AddField(
            model_name='show',
            name='is_discount_active',
            field=models.BooleanField(default=False, help_text='Enable or disable the discount for this show', verbose_name='Discount Active'),
        ),
    ]
