# Generated by Django 5.1.4 on 2024-12-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_show_discount_percent_show_is_discount_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='description',
            field=models.TextField(blank=True, help_text='Provide a brief description of the show'),
        ),
        migrations.AlterField(
            model_name='show',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Enter the discount percentage (e.g., 10.00 for 10%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='show',
            name='is_discount_active',
            field=models.BooleanField(default=False, help_text='Enable or disable the discount for this show'),
        ),
        migrations.AlterField(
            model_name='show',
            name='nationality',
            field=models.CharField(choices=[('Indian', 'Indian'), ('Foreigner', 'Foreigner')], max_length=20),
        ),
        migrations.AlterField(
            model_name='show',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='show',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='show',
            name='ticket_age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Child', 'Child')], max_length=10),
        ),
    ]
