# Generated by Django 5.1.4 on 2024-12-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_show_description_alter_show_discount_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='age_category',
        ),
        migrations.AddField(
            model_name='ticket',
            name='adult_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='child_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='total_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
