# Generated by Django 5.1.4 on 2024-12-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_ticket_age_category_ticket_adult_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.CharField(default='user', editable=False, max_length=400),
            preserve_default=False,
        ),
    ]
