# Generated by Django 5.1.4 on 2024-12-11 23:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_ticket_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(editable=False, max_length=400)),
                ('user', models.CharField(editable=False, max_length=400)),
                ('nationality', models.CharField(choices=[('Indian', 'Indian'), ('Foreigner', 'Foreigner')], max_length=20)),
                ('transaction_id', models.CharField(max_length=100)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('qr_code_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry_in', models.BooleanField(default=False)),
                ('entry_out', models.BooleanField(default=False)),
                ('dinosaur_show_in', models.BooleanField(default=False)),
                ('dinosaur_show_out', models.BooleanField(default=False)),
                ('ancient_statues_in', models.BooleanField(default=False)),
                ('ancient_statues_out', models.BooleanField(default=False)),
                ('ice_age_show_in', models.BooleanField(default=False)),
                ('ice_age_show_out', models.BooleanField(default=False)),
                ('photography', models.BooleanField(default=False)),
                ('entry_t', models.BooleanField(default=False)),
                ('dinosaur_t', models.BooleanField(default=False)),
                ('ancient_t', models.BooleanField(default=False)),
                ('ice_age_t', models.BooleanField(default=False)),
                ('photography_t', models.BooleanField(default=False)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
