# Generated by Django 5.1.4 on 2024-12-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_ticketsplit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsplit',
            name='age_category',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Child', 'Child')], default='admin', max_length=10),
            preserve_default=False,
        ),
    ]
