# Generated by Django 5.1.4 on 2024-12-12 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_ticketsplit_age_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsplit',
            name='ticket',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='home.ticket'),
            preserve_default=False,
        ),
    ]
