# Generated by Django 5.1.4 on 2024-12-12 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_ticketsplit_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsplit',
            name='ticket',
        ),
    ]
