# Generated by Django 5.1.4 on 2024-12-12 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_ticketsplit_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketSplit',
        ),
    ]
