# Generated by Django 5.1.4 on 2024-12-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_museum'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
