# Generated by Django 5.1.4 on 2024-12-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_show_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='museum_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
