# Generated by Django 4.2.24 on 2025-10-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_show_museum_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='session_id',
            field=models.CharField(max_length=400),
        ),
    ]
